name: "onCommentAdded"
on:
  discussion_comment:
    types: [created]
jobs:
  main:
    runs-on: ubuntu-22.04
    environment: Discussion
    steps:
      - name: "Send notification"
        run: |
          curl -i -H 'Content-Type: application/json' -d '${{ env.EVENT }}' -L https://us-central1-github-discussions-notifier.cloudfunctions.net/discussion-commentAdded
        env:
          EVENT: ${{ toJson(github.event) }}
