name: "onDicussionAnswered"
on:
  discussion:
    types: [answered]
jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: "Send notification"
        run: |
          curl -i -H 'Content-Type: application/json' -d '${{ env.EVENT }}' -L https://us-central1-github-discussions-notifier.cloudfunctions.net/discussion-resolved
        env:
          EVENT: ${{ toJson(github.event) }}
