name: "onDiscussionCreated"
on:
  discussion:
    types: [created]
jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: "Send notification"
        run: |
          cat "$GITHUB_EVENT_PATH" | sed 's/'\''/'\\\\\"'/g' |
          curl -H 'Content-Type: application/json' -d @- https://us-central1-github-discussions-notifier.cloudfunctions.net/discussion-created
